version: '3.7'

services:

  redis:
    image: redis
    command: [ 'redis-server', '--bind', 'redis', '--maxmemory', '256mb', '--maxmemory-policy', 'allkeys-lru', '--appendonly', 'yes' ]
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - 6379:6379

#  postgres:
#    image: "postgres" # use latest official postgres version
#    env_file:
#      - database.env # configure postgres
#    volumes:
#      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
#    restart: unless-stopped
#    expose:
#      - 5432
#    ports:
#      - 5432:5432

#  scheduler:
#    build:
#      context: .
#    restart: unless-stopped
#    command: [ 'celery', '-A', 'crawler.app', 'beat', '-S', 'redbeat.RedBeatScheduler', '--loglevel=INFO' ]
#    env_file:
#      - .env.dev
#    networks:
#      - default
#    depends_on:
#      - redis

  crawler:
    build:
      context: .
    restart: unless-stopped
    command: [ "celery", "-A", "crawler.app", "worker", "--concurrency=1",
               "--hostname=worker.crawler_q@%h", "--queues=crawler_q", "--loglevel=INFO" ]
    env_file:
      - .env.dev
    networks:
      - default
    depends_on:
      - redis

  counter:
    build:
      context: .
    restart: unless-stopped
    command: [ "celery", "-A", "crawler.app", "worker", "--concurrency=1",
               "--hostname=worker.counter_q@%h", "--queues=counter_q", "--loglevel=INFO" ]
    env_file:
      - .env.dev
    networks:
      - default
    depends_on:
      - redis

  flower:
    build:
      context: .
    restart: unless-stopped
    command: [ 'celery','-A', 'crawler.app', 'flower', '--port=5555', '--url-prefix=/flower' ]
    env_file:
      - .env.dev
    expose:
      - 5555
    networks:
      - default
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - flower

  prometheus:
    image: prom/prometheus
    command: [ "--config.file=/etc/prometheus/prometheus.yml", "--web.listen-address=0.0.0.0:9090" ]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

networks:
  default:
    driver: bridge

volumes:
  database-data:
  prometheus_data:
  grafana_data:
